---
name: ((deployment_name))
director_uuid: REPLACE_ME

releases:
- name: concourse
  version: "3.8.0"
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.8.0
  sha1: 99e134676df72e18c719ccfbd7977bd9449e6fd4
- name: garden-runc
  version: "1.11.0"
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.11.0
  sha1: ccb549bf3736ce3fe627f655eaca82006295b107
- name: postgres
  version: "25"
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=25
  sha1: 20929ee4b0c64fd97072a266311a6d00714124a7


stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: default
  stemcell: trusty
  azs: [z1]

  networks:
  - name: default
    static_ips: ((internal_ip))
  jobs:
  - name: atc
    release: concourse
    properties:
      # replace with your CI's externally reachable URL, e.g. https://ci.foo.com
      external_url: ((external_url))

      # replace with username/password, or configure GitHub auth
      basic_auth_username: admin
      basic_auth_password: ((concourse_admin_password))

      # replace with your SSL cert and key
      tls_cert: ((concourse-tls.certificate))
      tls_key: ((concourse-tls.private_key))
      tls_bind_port: 443

      postgresql:
        database: atc
        role:
          name: atc
          password: welcome1
      token_signing_key:
        private_key: ((token_signing_key.private_key))

  - name: tsa
    release: concourse
    properties:
      token_signing_key:
        private_key: ((token_signing_key.private_key))
      host_key:
        private_key: ((host_key.private_key))
        public_key: ((host_key.public_key))
      authorized_keys: [((worker_key.public_key))]


- name: db
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: large
  stemcell: trusty
  # replace with a disk type from your BOSH Director's cloud config
  persistent_disk_type: large
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: postgres
    release: postgres
    properties:
      databases:
        port: 5432
        databases:
          - name: atc
        roles:
          - name: atc
            password: welcome1


- name: worker
  instances: 1
  vm_type: large-disk
  stemcell: trusty
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: groundcrew
    release: concourse
    properties:
      host_key:
        public_key: ((host_key.public_key))
      tsa:
        worker_key:
          private_key: ((worker_key.private_key))
        host_public_key: ((host_key.public_key))
  - name: baggageclaim
    release: concourse
    properties: {}


  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
- name: concourse-ca
  type: certificate
  options:
    is_ca: true
    common_name: concourseCA
- name: concourse-tls
  type: certificate
  options:
    ca: concourse-ca
    common_name: ((internal_ip))
    alternative_names: [((internal_ip))]
- name: token_signing_key
  type: rsa
- name: host_key
  type: ssh
- name: worker_key
  type: ssh
