---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cgicloudnative/cfjump

inputs:
  - name: concourse-vault-test
  
run:
  path: concourse-vault-test/ci/test-pipeline/tasks/test-concourse-vault.sh