---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cgicloudnative/cfjump
    tag: latest

inputs:
  - name: create-concourse

run:
  path: create-concourse/ci/tasks/create-concourse-test.sh