#!/bin/bash
#########################################
#
#  Writes the values in Vault expected
#  by the pipeline.
#
#########################################

#  Token generated by the user. To generate the Token
#  go to the user's settings->Personal Access Token
vault write concourse/main/github/git-srv-password value=848dc0ba58fdce8a111f2d34867ec5cb1930c3d0
vault write concourse/main/github/git-srv-user value=srv-github-cgi

vault write concourse/main/github/test/username value=admin
