#!/bin/bash
#########################################
#
#  Writes the values in Vault expected
#  by the pipeline.
#
#########################################

#  Token generated by the user. To generate the Token
#  go to the user's settings->Personal Access Token
vault write concourse/main/github/git-srv-password value=3ebee1529074f4e33b772b1282dc8469d6981304
vault write concourse/main/github/git-srv-user value=srv-github-cgi

vault write concourse/main/test-username value=admin
